# Generated by Django 4.2.17 on 2026-02-15 16:53

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[("text", "Text Content"), ("list", "List Items")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("widget_title", models.CharField(max_length=50)),
                ("widget_number", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TextWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[("text", "Text Content"), ("list", "List Items")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("widget_title", models.CharField(max_length=50)),
                ("widget_number", models.PositiveSmallIntegerField(unique=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WidgetListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("text", models.CharField(max_length=150)),
                ("link", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institute.listwidget",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstituteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_estashment", models.DateField(blank=True, null=True)),
                ("logo", models.ImageField(upload_to="institute/")),
                (
                    "logo_small",
                    models.ImageField(blank=True, null=True, upload_to="institute/"),
                ),
                (
                    "site_favicon",
                    models.ImageField(blank=True, null=True, upload_to="institute"),
                ),
                (
                    "site_header",
                    models.CharField(
                        default="Django-School-Management",
                        help_text="Will be displayed in SuperAdmin Dashboard",
                        max_length=100,
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="Welcome to the Django-School-Management",
                        help_text="Title of the application/site",
                        max_length=100,
                    ),
                ),
                (
                    "super_admin_index_title",
                    models.CharField(
                        default="Django-School-Management Admin",
                        help_text="Will be displayed in SuperAdmin dashboard listing pages",
                        max_length=100,
                    ),
                ),
                ("motto", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=False, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
