# Generated by Django 4.2.17 on 2026-02-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Full Name")),
                ("photo", models.ImageField(upload_to="students/applicant/")),
                (
                    "fathers_name",
                    models.CharField(max_length=100, verbose_name="Father's Name"),
                ),
                (
                    "mothers_name",
                    models.CharField(max_length=100, verbose_name="Mother's Name"),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("01", "Bandarban"),
                            ("02", "Barguna"),
                            ("03", "Bogra"),
                            ("04", "Brahmanbaria"),
                            ("05", "Bagerhat"),
                            ("06", "Barisal"),
                            ("07", "Bhola"),
                            ("08", "Comilla"),
                            ("09", "Chandpur"),
                            ("10", "Chittagong"),
                            ("11", "Cox's Bazar"),
                            ("12", "Chuadanga"),
                            ("13", "Dhaka"),
                            ("14", "Dinajpur"),
                            ("15", "Faridpur"),
                            ("16", "Feni"),
                            ("17", "Gopalganj"),
                            ("18", "Gazipur"),
                            ("19", "Gaibandha"),
                            ("20", "Habiganj"),
                            ("21", "Jamalpur"),
                            ("22", "Jessore"),
                            ("23", "Jhenaidah"),
                            ("24", "Jaipurhat"),
                            ("25", "Jhalakati"),
                            ("26", "Kishoreganj"),
                            ("27", "Khulna"),
                            ("28", "Kurigram"),
                            ("29", "Khagrachari"),
                            ("30", "Kushtia"),
                            ("31", "Lakshmipur"),
                            ("32", "Lalmonirhat"),
                            ("33", "Manikganj"),
                            ("34", "Mymensingh"),
                            ("35", "Munshiganj"),
                            ("36", "Madaripur"),
                            ("37", "Magura"),
                            ("38", "Moulvibazar"),
                            ("39", "Meherpur"),
                            ("40", "Narayanganj"),
                            ("41", "Netrakona"),
                            ("42", "Narsingdi"),
                            ("43", "Narail"),
                            ("44", "Natore"),
                            ("45", "Nawabganj"),
                            ("46", "Nilphamari"),
                            ("47", "Noakhali"),
                            ("48", "Naogaon"),
                            ("49", "Pabna"),
                            ("50", "Pirojpur"),
                            ("51", "Patuakhali"),
                            ("52", "Panchagarh"),
                            ("53", "Rajbari"),
                            ("54", "Rajshahi"),
                            ("55", "Rangpur"),
                            ("56", "Rangamati"),
                            ("57", "Sherpur"),
                            ("58", "Satkhira"),
                            ("59", "Sirajganj"),
                            ("60", "Sylhet"),
                            ("61", "Sunamganj"),
                            ("62", "Shariatpur"),
                            ("63", "Tangail"),
                            ("64", "Thakurgaon"),
                        ],
                        max_length=2,
                    ),
                ),
                ("current_address", models.TextField()),
                ("permanent_address", models.TextField()),
                ("mobile_number", models.CharField(max_length=11)),
                ("guardian_mobile_number", models.CharField(max_length=11)),
                (
                    "tribal_status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Yes"), (0, "No")], default=0
                    ),
                ),
                (
                    "children_of_freedom_fighter",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Yes"), (0, "No")], default=0
                    ),
                ),
                (
                    "exam_name",
                    models.CharField(
                        choices=[
                            ("HSC", "Higher Secondary Certificate"),
                            ("SSC", "Secondary School Certificate"),
                            ("DAKHIL", "Dakhil Exam"),
                            ("VOCATIONAL", "Vocational"),
                        ],
                        max_length=10,
                    ),
                ),
                ("passing_year", models.CharField(max_length=4)),
                ("group", models.CharField(max_length=15)),
                ("board", models.CharField(max_length=100)),
                ("ssc_roll", models.CharField(max_length=10)),
                ("ssc_registration", models.CharField(max_length=12)),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "marksheet_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="students/applicants/marksheets/",
                        verbose_name="Upload Your Marksheet",
                    ),
                ),
                (
                    "admission_policy_agreement",
                    models.BooleanField(
                        default=False,
                        verbose_name="In publishing and graphic design, \n                                  Lorem ipsum is a placeholder text commonly used",
                    ),
                ),
                ("admitted", models.BooleanField(default=False)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "application_type",
                    models.CharField(
                        choices=[("1", "Online"), ("2", "Offline")],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "migration_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rejected", models.BooleanField(default=False)),
                ("assigned_as_student", models.BooleanField(default=False)),
                (
                    "choosen_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_students",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "roll",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                ("temp_serial", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "temporary_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "guardian_mobile",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("is_alumni", models.BooleanField(default=False)),
                ("is_dropped", models.BooleanField(default=False)),
                (
                    "ac_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.academicsession",
                    ),
                ),
                (
                    "admission_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.admissionstudent",
                    ),
                ),
                (
                    "admitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="academics.batch",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["semester", "roll", "registration_number"],
            },
        ),
        migrations.CreateModel(
            name="RegularStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CounselingComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("comment", models.CharField(max_length=150)),
                (
                    "counselor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrant_student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.admissionstudent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="counsel_comment",
            field=models.ManyToManyField(blank=True, to="students.counselingcomment"),
        ),
    ]
