# Generated by Django 4.2.17 on 2026-02-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0003_initial"),
        ("teachers", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionstudent",
            name="counseling_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counselors",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="department_choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.department"
            ),
        ),
    ]
